# Generated by Django 5.2.3 on 2025-07-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
